SET time_zone = "+00:00";
SET @@session.time_zone = "+00:00";
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;

START TRANSACTION;

COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
